import { useState, useMemo, useCallback } from 'react';
import {
  ChevronRight, ChevronDown, CheckCircle2, AlertTriangle, XCircle,
  Layers, Type, Code2, Paintbrush, Zap, Image, Loader2, ArrowUpToLine,
} from 'lucide-react';

// ─── Types ───────────────────────────────────────────────────────

interface FigmaNode {
  id: string;
  name: string;
  type: string;
  className?: string;
  htmlTag?: string;
  children?: FigmaNode[];
}

export interface PrePushReviewProps {
  nodes: FigmaNode[];
  nodeStyleOverrides: Record<string, Record<string, string>>;
  nodeAnimations: Record<string, { config: Record<string, unknown>; engine: string; trigger: string; presetId?: string }>;
  onPush: () => void;
  onCancel: () => void;
  isPushing?: boolean;
}

type SectionStatus = 'good' | 'warning' | 'error';

interface ReviewSection {
  id: string;
  title: string;
  icon: React.ElementType;
  status: SectionStatus;
  summary: string;
  details: string[];
}

// ─── Tree Walking Helpers ────────────────────────────────────────

const SEMANTIC_TAGS = new Set([
  'header', 'nav', 'main', 'section', 'article', 'aside', 'footer',
  'figure', 'figcaption', 'details', 'summary', 'dialog', 'time',
  'mark', 'address',
]);

const HEADING_TAGS = new Set(['h1', 'h2', 'h3', 'h4', 'h5', 'h6']);

const AUTO_GENERATED_PATTERNS = [/Frame/i, /Group/i, /\d{3,}/, /^Component/i, /^Instance/i];

interface TreeStats {
  totalElements: number;
  maxDepth: number;
  emptyContainers: string[];
  classNames: string[];
  autoGeneratedClasses: string[];
  semanticTagCount: number;
  nonSemanticTagCount: number;
  headingOrder: { tag: string; name: string }[];
  imageNodes: string[];
  nodesWithoutClassName: number;
}

function walkTree(
  nodes: FigmaNode[],
  depth: number = 0,
  stats: TreeStats = {
    totalElements: 0,
    maxDepth: 0,
    emptyContainers: [],
    classNames: [],
    autoGeneratedClasses: [],
    semanticTagCount: 0,
    nonSemanticTagCount: 0,
    headingOrder: [],
    imageNodes: [],
    nodesWithoutClassName: 0,
  },
): TreeStats {
  for (const node of nodes) {
    stats.totalElements++;
    stats.maxDepth = Math.max(stats.maxDepth, depth);

    if (node.className) {
      stats.classNames.push(node.className);
      const isAutoGenerated = AUTO_GENERATED_PATTERNS.some((p) => p.test(node.className!));
      if (isAutoGenerated) {
        stats.autoGeneratedClasses.push(node.className);
      }
    } else {
      stats.nodesWithoutClassName++;
    }

    const tag = node.htmlTag?.toLowerCase();
    if (tag) {
      if (SEMANTIC_TAGS.has(tag) || HEADING_TAGS.has(tag)) {
        stats.semanticTagCount++;
      } else {
        stats.nonSemanticTagCount++;
      }
      if (HEADING_TAGS.has(tag)) {
        stats.headingOrder.push({ tag, name: node.name });
      }
    } else {
      stats.nonSemanticTagCount++;
    }

    if (node.type.toLowerCase() === 'image' || node.type.toLowerCase() === 'img') {
      stats.imageNodes.push(node.name);
    }

    const children = node.children ?? [];
    const hasChildren = children.length > 0;
    const isContainer = ['frame', 'group', 'component', 'instance', 'div', 'section'].some(
      (t) => node.type.toLowerCase().includes(t),
    );
    if (isContainer && !hasChildren) {
      stats.emptyContainers.push(node.name);
    }

    if (hasChildren) {
      walkTree(children, depth + 1, stats);
    }
  }

  return stats;
}

function checkHeadingHierarchy(headings: { tag: string; name: string }[]): string[] {
  const issues: string[] = [];
  if (headings.length === 0) return issues;

  const h1Count = headings.filter((h) => h.tag === 'h1').length;
  if (h1Count === 0) {
    issues.push('No H1 tag found. Every page should have exactly one H1.');
  } else if (h1Count > 1) {
    issues.push(`Found ${h1Count} H1 tags. Only one H1 per page is recommended.`);
  }

  for (let i = 1; i < headings.length; i++) {
    const prevLevel = parseInt(headings[i - 1].tag.charAt(1), 10);
    const currLevel = parseInt(headings[i].tag.charAt(1), 10);
    if (currLevel > prevLevel + 1) {
      issues.push(
        `Heading skip: ${headings[i - 1].tag.toUpperCase()} "${headings[i - 1].name}" followed by ${headings[i].tag.toUpperCase()} "${headings[i].name}". Do not skip heading levels.`,
      );
    }
  }

  return issues;
}

// ─── Component ───────────────────────────────────────────────────

export function PrePushReview({
  nodes,
  nodeStyleOverrides,
  nodeAnimations,
  onPush,
  onCancel,
  isPushing = false,
}: PrePushReviewProps) {
  const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set());

  const stats = useMemo(() => walkTree(nodes), [nodes]);
  const headingIssues = useMemo(() => checkHeadingHierarchy(stats.headingOrder), [stats.headingOrder]);

  const styleCount = useMemo(() => {
    return Object.keys(nodeStyleOverrides).reduce((sum, key) => {
      return sum + Object.keys(nodeStyleOverrides[key]).length;
    }, 0);
  }, [nodeStyleOverrides]);

  const animationsByTrigger = useMemo(() => {
    const map: Record<string, number> = {};
    for (const anim of Object.values(nodeAnimations)) {
      const key = `${anim.engine}/${anim.trigger}`;
      map[key] = (map[key] || 0) + 1;
    }
    return map;
  }, [nodeAnimations]);

  const sections: ReviewSection[] = useMemo(() => {
    const result: ReviewSection[] = [];

    // 1. Structure
    const structureDetails: string[] = [
      `${stats.totalElements} elements total`,
      `Max nesting depth: ${stats.maxDepth}`,
    ];
    let structureStatus: SectionStatus = 'good';
    if (stats.emptyContainers.length > 0) {
      structureDetails.push(
        `${stats.emptyContainers.length} empty container${stats.emptyContainers.length > 1 ? 's' : ''}: ${stats.emptyContainers.slice(0, 5).join(', ')}${stats.emptyContainers.length > 5 ? '...' : ''}`,
      );
      structureStatus = 'warning';
    }
    if (stats.maxDepth > 10) {
      structureDetails.push('Deep nesting detected. Consider flattening the structure.');
      structureStatus = 'warning';
    }
    if (stats.totalElements === 0) {
      structureStatus = 'error';
    }
    result.push({
      id: 'structure',
      title: 'Structure',
      icon: Layers,
      status: structureStatus,
      summary: `${stats.totalElements} elements, depth ${stats.maxDepth}`,
      details: structureDetails,
    });

    // 2. Class Names
    const classDetails: string[] = [
      `${stats.classNames.length} classes defined`,
    ];
    let classStatus: SectionStatus = 'good';
    if (stats.nodesWithoutClassName > 0) {
      classDetails.push(`${stats.nodesWithoutClassName} element${stats.nodesWithoutClassName > 1 ? 's' : ''} without a class name`);
    }
    if (stats.autoGeneratedClasses.length > 0) {
      classDetails.push(
        `${stats.autoGeneratedClasses.length} auto-generated class name${stats.autoGeneratedClasses.length > 1 ? 's' : ''} detected:`,
      );
      stats.autoGeneratedClasses.slice(0, 8).forEach((c) => classDetails.push(`  .${c}`));
      if (stats.autoGeneratedClasses.length > 8) {
        classDetails.push(`  ...and ${stats.autoGeneratedClasses.length - 8} more`);
      }
      classStatus = 'warning';
    }
    result.push({
      id: 'classes',
      title: 'Class Names',
      icon: Code2,
      status: classStatus,
      summary: stats.autoGeneratedClasses.length > 0
        ? `${stats.autoGeneratedClasses.length} auto-generated`
        : `${stats.classNames.length} classes`,
      details: classDetails,
    });

    // 3. Semantic HTML
    const totalTags = stats.semanticTagCount + stats.nonSemanticTagCount;
    const semanticRatio = totalTags > 0 ? stats.semanticTagCount / totalTags : 0;
    const semanticDetails: string[] = [
      `${stats.semanticTagCount} semantic tag${stats.semanticTagCount !== 1 ? 's' : ''}, ${stats.nonSemanticTagCount} generic (div/span)`,
    ];
    let semanticStatus: SectionStatus = 'good';
    if (semanticRatio < 0.1 && totalTags > 3) {
      semanticDetails.push('Very few semantic tags. Consider using section, article, nav, header, footer.');
      semanticStatus = 'warning';
    }
    if (headingIssues.length > 0) {
      headingIssues.forEach((issue) => semanticDetails.push(issue));
      semanticStatus = headingIssues.some((i) => i.includes('skip')) ? 'error' : 'warning';
    }
    if (stats.headingOrder.length > 0) {
      semanticDetails.push(
        `Heading order: ${stats.headingOrder.map((h) => h.tag.toUpperCase()).join(' > ')}`,
      );
    }
    result.push({
      id: 'semantic',
      title: 'Semantic HTML',
      icon: Type,
      status: semanticStatus,
      summary: `${Math.round(semanticRatio * 100)}% semantic`,
      details: semanticDetails,
    });

    // 4. Styles
    const styledNodeCount = Object.keys(nodeStyleOverrides).length;
    const styleDetails: string[] = [
      `${styledNodeCount} element${styledNodeCount !== 1 ? 's' : ''} with style overrides`,
      `${styleCount} total CSS properties`,
    ];
    result.push({
      id: 'styles',
      title: 'Styles',
      icon: Paintbrush,
      status: 'good',
      summary: `${styleCount} properties on ${styledNodeCount} elements`,
      details: styleDetails,
    });

    // 5. Animations
    const animCount = Object.keys(nodeAnimations).length;
    const animDetails: string[] = [
      `${animCount} element${animCount !== 1 ? 's' : ''} with animations`,
    ];
    Object.entries(animationsByTrigger).forEach(([key, count]) => {
      animDetails.push(`  ${key}: ${count}`);
    });
    result.push({
      id: 'animations',
      title: 'Animations',
      icon: Zap,
      status: 'good',
      summary: animCount > 0 ? `${animCount} animated` : 'None',
      details: animDetails,
    });

    // 6. Images
    const imageDetails: string[] = [
      `${stats.imageNodes.length} image${stats.imageNodes.length !== 1 ? 's' : ''} found`,
    ];
    let imageStatus: SectionStatus = 'good';
    if (stats.imageNodes.length > 0) {
      imageDetails.push('Verify alt text is set for all images after pushing to Webflow.');
      imageStatus = 'warning';
    }
    result.push({
      id: 'images',
      title: 'Images',
      icon: Image,
      status: imageStatus,
      summary: stats.imageNodes.length > 0
        ? `${stats.imageNodes.length} images — check alt text`
        : 'No images',
      details: imageDetails,
    });

    return result;
  }, [stats, headingIssues, nodeStyleOverrides, nodeAnimations, animationsByTrigger, styleCount]);

  const hasBlockingErrors = sections.some((s) => s.status === 'error');

  const toggleSection = useCallback((id: string) => {
    setExpandedSections((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  }, []);

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        gap: 0,
        border: '1px solid var(--border-default)',
        borderRadius: 'var(--radius-lg)',
        backgroundColor: 'var(--bg-primary)',
        overflow: 'hidden',
        fontFamily: 'var(--font-sans)',
      }}
    >
      {/* Header */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          height: 44,
          padding: '0 16px',
          borderBottom: '1px solid var(--border-default)',
          backgroundColor: 'var(--bg-secondary)',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <ArrowUpToLine size={14} style={{ color: 'var(--text-tertiary)' }} />
          <span
            style={{
              fontSize: 'var(--text-sm)',
              fontWeight: 600,
              color: 'var(--text-primary)',
            }}
          >
            Pre-Push Review
          </span>
        </div>
        <span style={{ fontSize: 'var(--text-xs)', color: 'var(--text-tertiary)' }}>
          {sections.filter((s) => s.status === 'good').length}/{sections.length} checks passed
        </span>
      </div>

      {/* Sections */}
      <div style={{ flex: 1, overflowY: 'auto' }}>
        {sections.map((section) => {
          const isExpanded = expandedSections.has(section.id);
          const Icon = section.icon;

          return (
            <div key={section.id}>
              <button
                onClick={() => toggleSection(section.id)}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 10,
                  width: '100%',
                  height: 40,
                  padding: '0 16px',
                  border: 'none',
                  borderBottom: '1px solid var(--border-default)',
                  backgroundColor: 'transparent',
                  cursor: 'pointer',
                  fontFamily: 'var(--font-sans)',
                  transition: 'background-color 120ms ease',
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.backgroundColor = 'var(--surface-hover)';
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.backgroundColor = 'transparent';
                }}
              >
                {/* Chevron */}
                <span style={{ color: 'var(--text-tertiary)', flexShrink: 0 }}>
                  {isExpanded ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
                </span>

                {/* Status indicator */}
                <StatusIcon status={section.status} />

                {/* Section icon */}
                <Icon size={13} style={{ color: 'var(--text-tertiary)', flexShrink: 0 }} />

                {/* Title */}
                <span
                  style={{
                    fontSize: 'var(--text-sm)',
                    fontWeight: 500,
                    color: 'var(--text-primary)',
                    flex: 1,
                    textAlign: 'left',
                  }}
                >
                  {section.title}
                </span>

                {/* Summary */}
                <span
                  style={{
                    fontSize: 'var(--text-xs)',
                    color: 'var(--text-tertiary)',
                    flexShrink: 0,
                  }}
                >
                  {section.summary}
                </span>
              </button>

              {/* Expanded details */}
              {isExpanded && (
                <div
                  style={{
                    padding: '10px 16px 10px 56px',
                    borderBottom: '1px solid var(--border-default)',
                    backgroundColor: 'var(--bg-secondary)',
                  }}
                >
                  {section.details.map((detail, i) => (
                    <div
                      key={i}
                      style={{
                        fontSize: 'var(--text-xs)',
                        color: detail.startsWith('  ')
                          ? 'var(--text-tertiary)'
                          : 'var(--text-secondary)',
                        fontFamily: detail.startsWith('  .') ? 'var(--font-mono)' : 'var(--font-sans)',
                        lineHeight: 'var(--leading-normal)',
                        padding: '2px 0',
                      }}
                    >
                      {detail}
                    </div>
                  ))}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Footer / Actions */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'flex-end',
          gap: 8,
          padding: '12px 16px',
          borderTop: '1px solid var(--border-default)',
          backgroundColor: 'var(--bg-secondary)',
        }}
      >
        {hasBlockingErrors && (
          <span
            style={{
              flex: 1,
              fontSize: 'var(--text-xs)',
              color: 'var(--error)',
              display: 'flex',
              alignItems: 'center',
              gap: 4,
            }}
          >
            <XCircle size={12} />
            Resolve errors before pushing
          </span>
        )}

        <button
          onClick={onCancel}
          disabled={isPushing}
          style={{
            height: 36,
            padding: '0 16px',
            border: '1px solid var(--border-default)',
            borderRadius: 'var(--radius-md)',
            backgroundColor: 'transparent',
            fontSize: 'var(--text-sm)',
            fontWeight: 500,
            color: 'var(--text-secondary)',
            cursor: isPushing ? 'not-allowed' : 'pointer',
            fontFamily: 'var(--font-sans)',
            opacity: isPushing ? 0.5 : 1,
            transition: 'background-color 120ms ease',
          }}
          onMouseEnter={(e) => {
            if (!isPushing) e.currentTarget.style.backgroundColor = 'var(--surface-hover)';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.backgroundColor = 'transparent';
          }}
        >
          Cancel
        </button>

        <button
          onClick={onPush}
          disabled={hasBlockingErrors || isPushing}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: 6,
            height: 36,
            padding: '0 20px',
            border: 'none',
            borderRadius: 'var(--radius-md)',
            backgroundColor: hasBlockingErrors ? 'var(--bg-tertiary)' : 'var(--accent)',
            fontSize: 'var(--text-sm)',
            fontWeight: 600,
            color: hasBlockingErrors ? 'var(--text-tertiary)' : 'var(--text-on-accent)',
            cursor: hasBlockingErrors || isPushing ? 'not-allowed' : 'pointer',
            fontFamily: 'var(--font-sans)',
            opacity: isPushing ? 0.8 : 1,
            transition: 'opacity 120ms ease',
          }}
        >
          {isPushing && (
            <Loader2
              size={14}
              style={{
                animation: 'spin 1s linear infinite',
              }}
            />
          )}
          {isPushing ? 'Pushing...' : 'Push to Webflow'}
        </button>
      </div>

      {/* Keyframes for spinner */}
      <style>{`
        @keyframes spin {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
}

// ─── Status Icon Sub-component ───────────────────────────────────

function StatusIcon({ status }: { status: SectionStatus }) {
  if (status === 'good') {
    return <CheckCircle2 size={14} style={{ color: 'var(--accent)', flexShrink: 0 }} />;
  }
  if (status === 'warning') {
    return <AlertTriangle size={14} style={{ color: '#f59e0b', flexShrink: 0 }} />;
  }
  return <XCircle size={14} style={{ color: 'var(--error)', flexShrink: 0 }} />;
}
