import { useMemo, type ReactNode } from 'react';
import { X, FileText, Copy, Printer, Zap, Search, Bot, CheckCircle2, Film, StickyNote } from 'lucide-react';
import { toast } from 'sonner';
import { useProjectNotes } from '@/hooks/use-projects';
import { useProjectScores } from '@/hooks/use-project-scores';
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api';
import type { Project } from '@/types/project';

export interface HandoffReportDialogProps {
  projectId: string | null;
  projectName: string;
  open: boolean;
  onClose: () => void;
}

interface SetupProgress {
  completed: number;
  total: number;
}

interface AnimationCount {
  count: number;
}

function useProject(projectId: string | null) {
  return useQuery({
    queryKey: ['project', projectId],
    queryFn: () =>
      api.get<{ data: Project }>(`/projects/${projectId}`).then((r) => r.data),
    enabled: !!projectId,
  });
}

function useSetupProgress(projectId: string | null) {
  return useQuery({
    queryKey: ['setup-progress', projectId],
    queryFn: () =>
      api
        .get<{ data: SetupProgress }>(`/projects/${projectId}/setup/progress`)
        .then((r) => r.data),
    enabled: !!projectId,
    retry: false,
  });
}

function useAnimationCount(projectId: string | null) {
  return useQuery({
    queryKey: ['animation-count', projectId],
    queryFn: () =>
      api
        .get<{ data: AnimationCount }>(`/projects/${projectId}/animations/count`)
        .then((r) => r.data),
    enabled: !!projectId,
    retry: false,
  });
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

function scoreColor(score: number): string {
  const rounded = Math.round(score);
  if (rounded >= 80) return 'var(--accent)';
  if (rounded >= 60) return '#f59e0b';
  return 'var(--error)';
}

function scoreBg(score: number): string {
  const rounded = Math.round(score);
  if (rounded >= 80) return 'rgba(16, 185, 129, 0.08)';
  if (rounded >= 60) return 'rgba(245, 158, 11, 0.08)';
  return 'rgba(239, 68, 68, 0.08)';
}

function buildMarkdownReport(
  project: Project | undefined,
  projectName: string,
  scores: { speed: number | null; seo: number | null; aeo: number | null } | undefined,
  setupProgress: SetupProgress | undefined,
  animationCount: AnimationCount | undefined,
  notes: string | undefined,
): string {
  const lines: string[] = [];
  lines.push(`# Handoff Report: ${projectName}`);
  lines.push('');
  lines.push(`**Generated:** ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`);
  lines.push('');

  // Project overview
  lines.push('## Project Overview');
  lines.push('');
  lines.push(`- **Name:** ${projectName}`);
  if (project) {
    lines.push(`- **Created:** ${formatDate(project.createdAt)}`);
    if (project.webflowSiteId) {
      lines.push(`- **Webflow Site ID:** \`${project.webflowSiteId}\``);
    }
    if (project.figmaFileKey) {
      lines.push(`- **Figma File Key:** \`${project.figmaFileKey}\``);
    }
    lines.push(`- **Script Status:** ${project.scriptStatus.replace('_', ' ').toLowerCase()}`);
  }
  lines.push('');

  // Setup progress
  lines.push('## Setup Progress');
  lines.push('');
  if (setupProgress) {
    const pct = setupProgress.total > 0 ? Math.round((setupProgress.completed / setupProgress.total) * 100) : 0;
    lines.push(`- **Completion:** ${setupProgress.completed}/${setupProgress.total} items (${pct}%)`);
  } else {
    lines.push('- No setup data available');
  }
  lines.push('');

  // Audit summary
  lines.push('## Audit Summary');
  lines.push('');
  if (scores && (scores.speed !== null || scores.seo !== null || scores.aeo !== null)) {
    if (scores.speed !== null) lines.push(`- **Speed:** ${Math.round(scores.speed)}/100`);
    if (scores.seo !== null) lines.push(`- **SEO:** ${Math.round(scores.seo)}/100`);
    if (scores.aeo !== null) lines.push(`- **AEO:** ${Math.round(scores.aeo)}/100`);
  } else {
    lines.push('- No audit data available');
  }
  lines.push('');

  // Animations
  lines.push('## Animations');
  lines.push('');
  if (animationCount && animationCount.count > 0) {
    lines.push(`- **Animations assigned:** ${animationCount.count}`);
  } else {
    lines.push('- No animations assigned');
  }
  lines.push('');

  // Notes
  if (notes && notes.trim().length > 0) {
    lines.push('## Notes');
    lines.push('');
    lines.push(notes.trim());
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by Forge*');
  return lines.join('\n');
}

export function HandoffReportDialog({ projectId, projectName, open, onClose }: HandoffReportDialogProps) {
  const { data: project } = useProject(projectId);
  const { data: scores } = useProjectScores(projectId ?? '');
  const { data: notes } = useProjectNotes(projectId);
  const { data: setupProgress } = useSetupProgress(projectId);
  const { data: animationCount } = useAnimationCount(projectId);

  const setupPct = useMemo(() => {
    if (!setupProgress || setupProgress.total === 0) return null;
    return Math.round((setupProgress.completed / setupProgress.total) * 100);
  }, [setupProgress]);

  function handleCopyMarkdown() {
    const md = buildMarkdownReport(project, projectName, scores, setupProgress, animationCount, notes);
    navigator.clipboard.writeText(md).then(
      () => toast.success('Report copied to clipboard'),
      () => toast.error('Failed to copy report'),
    );
  }

  function handlePrint() {
    window.print();
  }

  if (!open) return null;

  return (
    <>
      {/* Backdrop */}
      <div
        onClick={onClose}
        style={{
          position: 'fixed',
          inset: 0,
          backgroundColor: 'rgba(0, 0, 0, 0.4)',
          zIndex: 998,
          animation: 'fadeIn 150ms ease-out',
        }}
      />

      {/* Panel */}
      <div
        style={{
          position: 'fixed',
          top: 0,
          right: 0,
          bottom: 0,
          width: 520,
          maxWidth: '100vw',
          backgroundColor: 'var(--bg-primary)',
          borderLeft: '1px solid var(--border-default)',
          zIndex: 999,
          display: 'flex',
          flexDirection: 'column',
          animation: 'slideInRight 200ms ease-out',
        }}
      >
        {/* Header */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: '16px 20px',
            borderBottom: '1px solid var(--border-default)',
            flexShrink: 0,
          }}
        >
          <div className="flex items-center" style={{ gap: 10 }}>
            <div
              className="flex items-center justify-center"
              style={{
                width: 28,
                height: 28,
                backgroundColor: 'var(--accent-subtle)',
                borderRadius: 'var(--radius-md)',
                flexShrink: 0,
              }}
            >
              <FileText size={14} style={{ color: 'var(--accent-text)' }} />
            </div>
            <div>
              <h2
                style={{
                  fontSize: 'var(--text-base)',
                  fontWeight: 600,
                  color: 'var(--text-primary)',
                  margin: 0,
                }}
              >
                Handoff Report
              </h2>
              <p
                style={{
                  fontSize: 'var(--text-xs)',
                  color: 'var(--text-tertiary)',
                  margin: '2px 0 0',
                }}
              >
                {projectName}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="flex items-center justify-center border-none bg-transparent cursor-pointer"
            style={{
              width: 28,
              height: 28,
              borderRadius: 'var(--radius-md)',
              color: 'var(--text-tertiary)',
              transition: 'color var(--duration-fast), background-color var(--duration-fast)',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.backgroundColor = 'var(--surface-active)';
              e.currentTarget.style.color = 'var(--text-primary)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.backgroundColor = 'transparent';
              e.currentTarget.style.color = 'var(--text-tertiary)';
            }}
            aria-label="Close handoff report"
          >
            <X size={16} />
          </button>
        </div>

        {/* Body */}
        <div
          style={{
            flex: 1,
            overflowY: 'auto',
            padding: 20,
            display: 'flex',
            flexDirection: 'column',
            gap: 24,
            minHeight: 0,
          }}
        >
          {/* Project Overview */}
          <ReportSection title="Project Overview">
            <ReportRow label="Name" value={projectName} />
            <ReportRow
              label="Created"
              value={project ? formatDate(project.createdAt) : '\u2014'}
            />
            <ReportRow
              label="Webflow Site ID"
              value={project?.webflowSiteId ?? '\u2014'}
              mono={!!project?.webflowSiteId}
            />
            <ReportRow
              label="Figma File"
              value={project?.figmaFileKey ? 'Linked' : 'Not linked'}
            />
            <ReportRow
              label="Script Status"
              value={
                project
                  ? project.scriptStatus.replace('_', ' ').toLowerCase()
                  : '\u2014'
              }
            />
          </ReportSection>

          {/* Setup Progress */}
          <ReportSection title="Setup Progress" icon={<CheckCircle2 size={14} />}>
            {setupProgress ? (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                <div className="flex items-center justify-between">
                  <span
                    style={{
                      fontSize: 'var(--text-sm)',
                      color: 'var(--text-secondary)',
                    }}
                  >
                    {setupProgress.completed} of {setupProgress.total} items complete
                  </span>
                  <span
                    style={{
                      fontSize: 'var(--text-sm)',
                      fontWeight: 600,
                      fontFamily: 'var(--font-mono)',
                      color: 'var(--text-primary)',
                    }}
                  >
                    {setupPct}%
                  </span>
                </div>
                <div
                  style={{
                    height: 4,
                    borderRadius: 2,
                    backgroundColor: 'var(--surface-hover)',
                    overflow: 'hidden',
                  }}
                >
                  <div
                    style={{
                      height: '100%',
                      width: `${setupPct ?? 0}%`,
                      backgroundColor: 'var(--accent)',
                      borderRadius: 2,
                      transition: 'width 300ms ease-out',
                    }}
                  />
                </div>
              </div>
            ) : (
              <EmptyField text="No setup data available" />
            )}
          </ReportSection>

          {/* Audit Summary */}
          <ReportSection title="Audit Summary">
            {scores && (scores.speed !== null || scores.seo !== null || scores.aeo !== null) ? (
              <div className="flex items-center" style={{ gap: 10, flexWrap: 'wrap' }}>
                {scores.speed !== null && (
                  <ScoreChip icon={<Zap size={12} />} label="Speed" score={scores.speed} />
                )}
                {scores.seo !== null && (
                  <ScoreChip icon={<Search size={12} />} label="SEO" score={scores.seo} />
                )}
                {scores.aeo !== null && (
                  <ScoreChip icon={<Bot size={12} />} label="AEO" score={scores.aeo} />
                )}
              </div>
            ) : (
              <EmptyField text="No audit data available" />
            )}
          </ReportSection>

          {/* Animations */}
          <ReportSection title="Animations" icon={<Film size={14} />}>
            {animationCount && animationCount.count > 0 ? (
              <div className="flex items-center" style={{ gap: 8 }}>
                <span
                  style={{
                    fontSize: 'var(--text-xl)',
                    fontWeight: 700,
                    fontFamily: 'var(--font-mono)',
                    color: 'var(--text-primary)',
                    lineHeight: 1,
                  }}
                >
                  {animationCount.count}
                </span>
                <span
                  style={{
                    fontSize: 'var(--text-sm)',
                    color: 'var(--text-secondary)',
                  }}
                >
                  animation{animationCount.count !== 1 ? 's' : ''} assigned
                </span>
              </div>
            ) : (
              <EmptyField text="No animations assigned" />
            )}
          </ReportSection>

          {/* Notes */}
          <ReportSection title="Notes" icon={<StickyNote size={14} />}>
            {notes && notes.trim().length > 0 ? (
              <p
                style={{
                  fontSize: 'var(--text-sm)',
                  color: 'var(--text-secondary)',
                  lineHeight: 'var(--leading-relaxed)',
                  margin: 0,
                  whiteSpace: 'pre-wrap',
                  wordBreak: 'break-word',
                  maxHeight: 160,
                  overflowY: 'auto',
                }}
              >
                {notes.trim()}
              </p>
            ) : (
              <EmptyField text="No notes" />
            )}
          </ReportSection>
        </div>

        {/* Footer */}
        <div
          style={{
            padding: '12px 20px',
            borderTop: '1px solid var(--border-default)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'flex-end',
            gap: 8,
            flexShrink: 0,
          }}
        >
          <FooterButton
            icon={<Copy size={14} />}
            label="Copy as Markdown"
            onClick={handleCopyMarkdown}
          />
          <FooterButton
            icon={<Printer size={14} />}
            label="Print"
            onClick={handlePrint}
          />
        </div>
      </div>
    </>
  );
}

/* ── Subcomponents ── */

function ReportSection({
  title,
  icon,
  children,
}: {
  title: string;
  icon?: ReactNode;
  children: ReactNode;
}) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
      <div className="flex items-center" style={{ gap: 6 }}>
        {icon && (
          <span style={{ color: 'var(--text-tertiary)', display: 'flex' }}>{icon}</span>
        )}
        <h3
          style={{
            fontSize: 'var(--text-xs)',
            fontWeight: 600,
            color: 'var(--text-tertiary)',
            textTransform: 'uppercase',
            letterSpacing: '0.04em',
            margin: 0,
          }}
        >
          {title}
        </h3>
      </div>
      <div
        style={{
          backgroundColor: 'var(--bg-secondary)',
          border: '1px solid var(--border-subtle)',
          borderRadius: 'var(--radius-md)',
          padding: 14,
          display: 'flex',
          flexDirection: 'column',
          gap: 8,
        }}
      >
        {children}
      </div>
    </div>
  );
}

function ReportRow({
  label,
  value,
  mono = false,
}: {
  label: string;
  value: string;
  mono?: boolean;
}) {
  return (
    <div
      className="flex items-center justify-between"
      style={{ gap: 12 }}
    >
      <span
        style={{
          fontSize: 'var(--text-sm)',
          color: 'var(--text-tertiary)',
          flexShrink: 0,
        }}
      >
        {label}
      </span>
      <span
        style={{
          fontSize: 'var(--text-sm)',
          color: 'var(--text-primary)',
          fontWeight: 500,
          fontFamily: mono ? 'var(--font-mono)' : 'var(--font-sans)',
          textAlign: 'right',
          overflow: 'hidden',
          textOverflow: 'ellipsis',
          whiteSpace: 'nowrap',
          minWidth: 0,
        }}
      >
        {value}
      </span>
    </div>
  );
}

function ScoreChip({
  icon,
  label,
  score,
}: {
  icon: ReactNode;
  label: string;
  score: number;
}) {
  const rounded = Math.round(score);
  return (
    <div
      className="flex items-center"
      style={{
        gap: 6,
        padding: '6px 10px',
        borderRadius: 'var(--radius-md)',
        backgroundColor: scoreBg(score),
        border: `1px solid ${scoreColor(score)}20`,
      }}
    >
      <span style={{ color: scoreColor(score), display: 'flex' }}>{icon}</span>
      <span
        style={{
          fontSize: 'var(--text-xs)',
          color: 'var(--text-secondary)',
          fontWeight: 500,
        }}
      >
        {label}
      </span>
      <span
        style={{
          fontSize: 'var(--text-sm)',
          fontWeight: 700,
          fontFamily: 'var(--font-mono)',
          color: scoreColor(score),
        }}
      >
        {rounded}
      </span>
    </div>
  );
}

function EmptyField({ text }: { text: string }) {
  return (
    <span
      style={{
        fontSize: 'var(--text-sm)',
        color: 'var(--text-tertiary)',
        fontStyle: 'italic',
      }}
    >
      {text}
    </span>
  );
}

function FooterButton({
  icon,
  label,
  onClick,
}: {
  icon: ReactNode;
  label: string;
  onClick: () => void;
}) {
  return (
    <button
      onClick={onClick}
      className="flex items-center justify-center border-none cursor-pointer"
      style={{
        height: 36,
        padding: '0 14px',
        gap: 6,
        borderRadius: 'var(--radius-md)',
        backgroundColor: 'var(--bg-secondary)',
        border: '1px solid var(--border-default)',
        color: 'var(--text-secondary)',
        fontSize: 'var(--text-sm)',
        fontWeight: 500,
        fontFamily: 'var(--font-sans)',
        transition: 'border-color var(--duration-fast), color var(--duration-fast), background-color var(--duration-fast)',
      }}
      onMouseEnter={(e) => {
        e.currentTarget.style.borderColor = 'var(--border-strong)';
        e.currentTarget.style.color = 'var(--text-primary)';
        e.currentTarget.style.backgroundColor = 'var(--surface-hover)';
      }}
      onMouseLeave={(e) => {
        e.currentTarget.style.borderColor = 'var(--border-default)';
        e.currentTarget.style.color = 'var(--text-secondary)';
        e.currentTarget.style.backgroundColor = 'var(--bg-secondary)';
      }}
    >
      {icon}
      <span>{label}</span>
    </button>
  );
}
