import { guideStyles as s } from './guide-styles';

export function ScalingSystemGuide() {
  return (
    <div style={s.section}>
      <h2 style={s.h2}>What is Fluid Scaling?</h2>
      <p style={s.p}>
        Fluid scaling adjusts the root font size (<code style={s.code}>html font-size</code>)
        based on the viewport width. Since <code style={s.code}>rem</code> values are relative
        to the root font size, everything sized in rem scales proportionally across all screen
        sizes.
      </p>
      <p style={s.p}>
        This eliminates the need for media query overrides on font sizes, spacing, and component
        dimensions. One set of rem values works everywhere. The design scales smoothly between
        breakpoints instead of jumping between fixed sizes.
      </p>

      <h3 style={s.h3}>How it works technically</h3>
      <p style={s.p}>
        Forge generates a CSS <code style={s.code}>clamp()</code> function for each breakpoint
        range. The function calculates the ideal font size based on the current viewport width,
        with minimum and maximum bounds to prevent extreme scaling.
      </p>
      <pre style={s.codeBlock}>
        <code>{`/* Generated by Forge for Desktop breakpoint */
html {
  font-size: clamp(
    14px,                          /* minimum */
    calc(14px + (16 - 14) * ((100vw - 992px) / (1920 - 992))),  /* fluid */
    16px                           /* maximum */
  );
}

/* At 992px viewport → 14px base */
/* At 1440px viewport → ~15.2px base (the ideal) */
/* At 1920px viewport → 16px base */`}</code>
      </pre>

      <hr style={s.divider} />

      <h2 style={s.h2}>Configuring Breakpoints</h2>
      <p style={s.p}>
        Each breakpoint has four values:
      </p>
      <ul style={s.ul}>
        <li>
          <strong style={{ color: 'var(--text-primary)' }}>Base font size</strong> — The root font
          size at the ideal width (e.g., 16px for desktop).
        </li>
        <li>
          <strong style={{ color: 'var(--text-primary)' }}>Ideal width</strong> — The viewport
          width where the base font size is exactly as set (e.g., 1440px).
        </li>
        <li>
          <strong style={{ color: 'var(--text-primary)' }}>Min width</strong> — The narrowest
          viewport for this breakpoint range (e.g., 992px).
        </li>
        <li>
          <strong style={{ color: 'var(--text-primary)' }}>Max width</strong> — The widest viewport
          for this breakpoint range (e.g., 1920px).
        </li>
      </ul>

      <h3 style={s.h3}>Default breakpoints</h3>
      <pre style={s.codeBlock}>
        <code>{`Desktop:          base 16px,  ideal 1440px, min 992px,  max 1920px
Tablet:           base 15px,  ideal 834px,  min 768px,  max 991px
Mobile Landscape: base 14px,  ideal 550px,  min 480px,  max 767px
Mobile Portrait:  base 13px,  ideal 375px,  min 320px,  max 479px`}</code>
      </pre>

      <div style={s.tip}>
        <div style={s.calloutLabel}>Tip</div>
        When you import a Figma file, Forge detects the frame width and auto-sets the desktop
        "ideal width" to match your design. If your Figma frames are 1440px wide, the ideal
        width defaults to 1440px.
      </div>

      <h2 style={s.h2}>Preview</h2>
      <p style={s.p}>
        Each breakpoint card in the scaling configuration shows a real-time preview line:
      </p>
      <pre style={s.codeBlock}>
        <code>{`At 1440px → 16px (ideal)
At 992px  → 14px (min)
At 1920px → 16px (max, clamped)`}</code>
      </pre>
      <p style={s.p}>
        This lets you see the actual computed font size at any viewport width before pushing the
        code to Webflow.
      </p>

      <hr style={s.divider} />

      <h2 style={s.h2}>Pushing to Webflow</h2>
      <ol style={s.ol}>
        <li>
          Configure your breakpoints in the Scaling System page.
        </li>
        <li>
          Click "Generate CSS". Forge produces the{' '}
          <code style={s.code}>clamp()</code> rules for all breakpoints.
        </li>
        <li>
          Review the generated code in the code viewer.
        </li>
        <li>
          Click "Push to Webflow" to inject the CSS into your site&apos;s{' '}
          <code style={s.code}>{'<head>'}</code> via MCP. Alternatively, click "Copy" and
          paste it into Webflow&apos;s custom code settings manually.
        </li>
      </ol>

      <div style={s.note}>
        <div style={s.calloutLabel}>Note</div>
        After pushing the scaling CSS, all rem-based values in your Webflow project will scale
        fluidly. Make sure your typography, spacing, and component sizing use rem units in
        Webflow for the scaling to take effect.
      </div>

      <h2 style={s.h2}>How Scaling Affects Other Modules</h2>
      <p style={s.p}>
        When the scaling system is configured for a project, it integrates with several other
        parts of Forge:
      </p>
      <ul style={s.ul}>
        <li>
          <strong style={{ color: 'var(--text-primary)' }}>Live Preview</strong> — The scaling CSS
          is injected into the preview iframe so rem values render correctly at any preview width.
        </li>
        <li>
          <strong style={{ color: 'var(--text-primary)' }}>Unit conversion</strong> — The unit
          input component uses your scaling config&apos;s base font size for px-to-rem conversion.
          At 16px base: 24px = 1.5rem.
        </li>
        <li>
          <strong style={{ color: 'var(--text-primary)' }}>Animation distances</strong> — When
          using rem for animation distance values, the data attributes include the unit:{' '}
          <code style={s.code}>data-anim-distance="2.75rem"</code>.
        </li>
        <li>
          <strong style={{ color: 'var(--text-primary)' }}>Master script</strong> — The generated
          animation script respects rem values in all parameters.
        </li>
      </ul>

      <h2 style={s.h2}>When to Use Fluid Scaling</h2>
      <p style={s.p}>
        Fluid scaling works best for marketing sites, landing pages, and content-heavy sites
        where text and spacing should feel proportional at every screen size. It is less necessary
        for web applications with fixed-width UI elements (toolbars, sidebars, data tables).
      </p>

      <div style={s.tip}>
        <div style={s.calloutLabel}>Tip</div>
        Start with the default breakpoints and adjust only if the design does not look right at
        specific viewport widths. The defaults work well for most standard Webflow projects.
      </div>
    </div>
  );
}
