import { useEffect, useState, useCallback, useMemo } from 'react';
import { X, Copy, Zap, Loader2, Code, Check, ArrowLeftRight, ChevronDown, Paintbrush } from 'lucide-react';
import { toast } from 'sonner';
import { useTemplate } from '@/hooks/use-templates';
import { TemplatePreview } from './template-preview';
import { StylePanel } from '@/components/shared/editors';
import type { CSSStyles } from '@/components/shared/editors';
import type { TemplateNode } from '@/types/template';

function nodeToHtml(node: TemplateNode, indent: number = 0): string {
  const pad = '  '.repeat(indent);
  const cls = node.className ? ` class="${node.className}"` : '';
  const extra = node.attrs
    ? Object.entries(node.attrs).map(([k, v]) => ` ${k}="${v}"`).join('')
    : '';
  const selfClosing = ['img', 'br', 'hr', 'input'].includes(node.tag);
  if (selfClosing) return `${pad}<${node.tag}${cls}${extra} />`;
  const hasKids = node.children && node.children.length > 0;
  if (!hasKids && !node.text) return `${pad}<${node.tag}${cls}${extra}></${node.tag}>`;
  if (!hasKids && node.text) return `${pad}<${node.tag}${cls}${extra}>${node.text}</${node.tag}>`;
  const kids = node.children!.map((c) => nodeToHtml(c, indent + 1)).join('\n');
  const txt = node.text ? `\n${pad}  ${node.text}` : '';
  return `${pad}<${node.tag}${cls}${extra}>${txt}\n${kids}\n${pad}</${node.tag}>`;
}

/** Generate Webflow Designer API script to build the template structure */
function generateDesignerScript(
  node: TemplateNode,
  animationAttrs: Record<string, string> | null,
  varName: string = 'root',
  indent: number = 0,
): string {
  const pad = '  '.repeat(indent);
  const lines: string[] = [];

  if (indent === 0) {
    lines.push('// Webflow Designer API — auto-generated by Forge');
    lines.push('// Select a parent element on the canvas, then run this script');
    lines.push('');
    lines.push('const selectedEl = await webflow.getSelectedElement();');
    lines.push('if (!selectedEl || !selectedEl.children) {');
    lines.push('  console.error("Select a container element first");');
    lines.push('} else {');
    lines.push(`  const ${varName} = webflow.elementBuilder(webflow.elementPresets.DOM);`);
  } else {
    lines.push(`${pad}const ${varName} = ${indent === 1 ? 'root' : varName.replace(/_\d+$/, '')}.append(webflow.elementPresets.DOM);`);
  }

  lines.push(`${pad}${varName}.setTag('${node.tag}');`);

  if (node.className) {
    lines.push(`${pad}${varName}.setAttribute('class', '${node.className}');`);
  }

  if (node.text) {
    lines.push(`${pad}${varName}.setTextContent('${node.text.replace(/'/g, "\\'")}');`);
  }

  if (node.attrs) {
    for (const [key, value] of Object.entries(node.attrs)) {
      lines.push(`${pad}${varName}.setAttribute('${key}', '${value.replace(/'/g, "\\'")}');`);
    }
  }

  // Add animation attributes to root element
  if (indent === 0 && animationAttrs) {
    for (const [key, value] of Object.entries(animationAttrs)) {
      lines.push(`  ${varName}.setAttribute('${key}', '${value.replace(/'/g, "\\'")}');`);
    }
  }

  if (node.children && node.children.length > 0) {
    node.children.forEach((child, i) => {
      const childVar = `${varName}_${i}`;
      lines.push('');
      lines.push(...generateDesignerScript(child, null, childVar, indent + 1).split('\n'));
    });
  }

  if (indent === 0) {
    lines.push('');
    lines.push('  await selectedEl.append(root);');
    lines.push('  await webflow.notify({ type: "Success", message: "Template added!" });');
    lines.push('}');
  }

  return lines.join('\n');
}

interface TemplateDetailPanelProps {
  templateId: string | null;
  open: boolean;
  onClose: () => void;
  onDuplicate?: (id: string) => void;
  onCompare?: (id: string) => void;
}

/** Find a node by path index in the template tree */
function findNodeByPath(root: TemplateNode, path: number[]): TemplateNode | null {
  let current: TemplateNode = root;
  for (const idx of path) {
    if (!current.children || idx >= current.children.length) return null;
    current = current.children[idx];
  }
  return current;
}

/** Build a flat list of nodes with their paths for selection */
function flattenNodes(node: TemplateNode, path: number[] = []): Array<{ node: TemplateNode; path: number[]; depth: number }> {
  const result: Array<{ node: TemplateNode; path: number[]; depth: number }> = [
    { node, path, depth: path.length },
  ];
  if (node.children) {
    node.children.forEach((child, i) => {
      result.push(...flattenNodes(child, [...path, i]));
    });
  }
  return result;
}

/** Extract styles from template node inline styles (from styles record) */
function extractTemplateNodeStyles(
  node: TemplateNode,
  templateStyles: Record<string, unknown> | null,
): CSSStyles {
  const styles: CSSStyles = {};
  // Check if template has styles keyed by className
  if (templateStyles && node.className) {
    const nodeStyles = templateStyles[`.${node.className}`] as Record<string, string> | undefined;
    if (nodeStyles) {
      Object.assign(styles, nodeStyles);
    }
  }
  return styles;
}

export function TemplateDetailPanel({ templateId, open, onClose, onDuplicate, onCompare }: TemplateDetailPanelProps) {
  const { data: template, isLoading } = useTemplate(templateId);
  const [selectedPath, setSelectedPath] = useState<number[] | null>(null);
  const [showStyleEditor, setShowStyleEditor] = useState(false);
  const [styleOverrides, setStyleOverrides] = useState<Record<string, CSSStyles>>({});

  // Reset selection when template changes
  useEffect(() => {
    setSelectedPath(null);
    setShowStyleEditor(false);
    setStyleOverrides({});
  }, [templateId]);

  const selectedNode = useMemo(() => {
    if (!template || !selectedPath) return null;
    return findNodeByPath(template.structure, selectedPath);
  }, [template, selectedPath]);

  const selectedNodeKey = selectedPath ? selectedPath.join('-') : '';

  const selectedNodeStyles = useMemo<CSSStyles>(() => {
    if (!selectedNode || !template) return {};
    const base = extractTemplateNodeStyles(selectedNode, template.styles);
    const overrides = selectedNodeKey ? styleOverrides[selectedNodeKey] : undefined;
    return overrides ? { ...base, ...overrides } : base;
  }, [selectedNode, template, selectedNodeKey, styleOverrides]);

  const handleStyleChange = useCallback(
    (property: string, value: string) => {
      if (!selectedNodeKey) return;
      setStyleOverrides((prev) => ({
        ...prev,
        [selectedNodeKey]: {
          ...(prev[selectedNodeKey] ?? {}),
          [property]: value,
        },
      }));
    },
    [selectedNodeKey],
  );

  // Merge overrides into template styles for preview
  const mergedStyles = useMemo(() => {
    if (!template?.styles) return template?.styles ?? null;
    const result = { ...template.styles } as Record<string, Record<string, string>>;
    for (const [pathKey, overrides] of Object.entries(styleOverrides)) {
      // Reconstruct className from path
      const pathParts = pathKey.split('-').map(Number);
      const node = findNodeByPath(template.structure, pathParts);
      if (node?.className) {
        const selector = `.${node.className}`;
        result[selector] = {
          ...((result[selector] as Record<string, string>) ?? {}),
          ...overrides,
        };
      }
    }
    return result;
  }, [template, styleOverrides]);

  // Close on Escape
  useEffect(() => {
    if (!open) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [open, onClose]);

  return (
    <>
      {/* Backdrop */}
      {open && (
        <div
          onClick={onClose}
          style={{
            position: 'fixed',
            inset: 0,
            backgroundColor: 'rgba(0,0,0,0.3)',
            zIndex: 90,
            transition: 'opacity 200ms ease',
          }}
        />
      )}

      {/* Panel */}
      <div
        style={{
          position: 'fixed',
          top: 0,
          right: 0,
          bottom: 0,
          width: '50%',
          maxWidth: 640,
          minWidth: 380,
          backgroundColor: 'var(--bg-primary)',
          borderLeft: '1px solid var(--border-default)',
          zIndex: 100,
          transform: open ? 'translateX(0)' : 'translateX(100%)',
          transition: 'transform 200ms ease',
          display: 'flex',
          flexDirection: 'column',
        }}
      >
        {/* Header */}
        <div
          className="flex items-center justify-between shrink-0"
          style={{
            height: 48,
            padding: '0 16px',
            borderBottom: '1px solid var(--border-default)',
          }}
        >
          <span
            className="font-medium"
            style={{ fontSize: 'var(--text-sm)', color: 'var(--text-primary)' }}
          >
            {template?.name ?? 'Template Detail'}
          </span>
          <button
            onClick={onClose}
            className="flex items-center justify-center border-none bg-transparent cursor-pointer"
            style={{ width: 28, height: 28, color: 'var(--text-tertiary)' }}
          >
            <X size={16} />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-auto" style={{ padding: 16 }}>
          {isLoading && (
            <div
              className="flex items-center justify-center"
              style={{ height: 200, color: 'var(--text-tertiary)' }}
            >
              <Loader2 size={20} className="animate-spin" style={{ color: 'var(--accent)' }} />
            </div>
          )}

          {template && (
            <div className="flex flex-col" style={{ gap: 16 }}>
              {/* Meta */}
              <div className="flex flex-col" style={{ gap: 8 }}>
                {template.description && (
                  <p
                    style={{
                      margin: 0,
                      fontSize: 'var(--text-sm)',
                      color: 'var(--text-secondary)',
                    }}
                  >
                    {template.description}
                  </p>
                )}

                <div className="flex items-center" style={{ gap: 6 }}>
                  <span
                    style={{
                      fontSize: 'var(--text-xs)',
                      fontWeight: 600,
                      color: template.type === 'STYLED' ? '#8b5cf6' : 'var(--text-tertiary)',
                      backgroundColor:
                        template.type === 'STYLED'
                          ? 'rgba(139, 92, 246, 0.1)'
                          : 'var(--surface-hover)',
                      padding: '2px 8px',
                      borderRadius: 'var(--radius-sm)',
                      textTransform: 'uppercase',
                    }}
                  >
                    {template.type}
                  </span>
                  <span
                    style={{
                      fontSize: 'var(--text-xs)',
                      color: 'var(--text-tertiary)',
                      backgroundColor: 'var(--surface-hover)',
                      padding: '2px 8px',
                      borderRadius: 'var(--radius-sm)',
                    }}
                  >
                    {template.category}
                  </span>
                  {template.animationAttrs && Object.keys(template.animationAttrs).length > 0 && (
                    <span
                      className="flex items-center"
                      style={{
                        gap: 3,
                        fontSize: 'var(--text-xs)',
                        color: '#f59e0b',
                        backgroundColor: 'rgba(245, 158, 11, 0.1)',
                        padding: '2px 8px',
                        borderRadius: 'var(--radius-sm)',
                      }}
                    >
                      <Zap size={10} />
                      Animated
                    </span>
                  )}
                </div>

                {template.tags.length > 0 && (
                  <div className="flex items-center" style={{ gap: 4, flexWrap: 'wrap' }}>
                    {template.tags.map((tag) => (
                      <span
                        key={tag}
                        style={{
                          fontSize: 'var(--text-xs)',
                          color: 'var(--text-tertiary)',
                          border: '1px solid var(--border-default)',
                          padding: '1px 6px',
                          borderRadius: 'var(--radius-sm)',
                        }}
                      >
                        {tag}
                      </span>
                    ))}
                  </div>
                )}
              </div>

              {/* Preview (with merged styles) */}
              <CollapsibleSection title="Preview" defaultOpen>
                <TemplatePreview structure={template.structure} styles={mergedStyles} />
              </CollapsibleSection>

              {/* Structure tree with selection */}
              <div
                style={{
                  border: '1px solid var(--border-default)',
                  borderRadius: 'var(--radius-lg)',
                  overflow: 'hidden',
                }}
              >
                <div
                  className="flex items-center justify-between"
                  style={{
                    height: 36,
                    padding: '0 12px',
                    borderBottom: '1px solid var(--border-default)',
                    backgroundColor: 'var(--bg-secondary)',
                  }}
                >
                  <span
                    className="font-medium"
                    style={{ fontSize: 'var(--text-xs)', color: 'var(--text-primary)' }}
                  >
                    Structure
                  </span>
                  <span style={{ fontSize: 'var(--text-xs)', color: 'var(--text-tertiary)' }}>
                    {countNodes(template.structure)} elements — click to edit styles
                  </span>
                </div>
                <div style={{ padding: '8px 4px', maxHeight: 400, overflow: 'auto' }}>
                  <StructureNode
                    node={template.structure}
                    depth={0}
                    path={[]}
                    selectedPath={selectedPath}
                    onSelect={(path) => {
                      if (selectedPath && path.join('-') === selectedPath.join('-')) {
                        setSelectedPath(null);
                        setShowStyleEditor(false);
                      } else {
                        setSelectedPath(path);
                        setShowStyleEditor(true);
                      }
                    }}
                  />
                </div>
              </div>

              {/* Inline style editor for selected node */}
              {selectedNode && showStyleEditor && (
                <div
                  style={{
                    border: '1px solid var(--border-default)',
                    borderRadius: 'var(--radius-lg)',
                    overflow: 'hidden',
                  }}
                >
                  <div
                    className="flex items-center justify-between"
                    style={{
                      height: 36,
                      padding: '0 12px',
                      borderBottom: '1px solid var(--border-default)',
                      backgroundColor: 'var(--bg-secondary)',
                    }}
                  >
                    <div className="flex items-center" style={{ gap: 6 }}>
                      <Paintbrush size={12} style={{ color: 'var(--accent-text)' }} />
                      <span
                        className="font-medium"
                        style={{ fontSize: 'var(--text-xs)', color: 'var(--text-primary)' }}
                      >
                        Styles
                      </span>
                      <span
                        style={{
                          fontFamily: 'var(--font-mono)',
                          fontSize: 10,
                          color: 'var(--accent-text)',
                          backgroundColor: 'var(--accent-subtle)',
                          padding: '1px 5px',
                          borderRadius: 'var(--radius-sm)',
                        }}
                      >
                        .{selectedNode.className}
                      </span>
                    </div>
                    <button
                      onClick={() => {
                        setSelectedPath(null);
                        setShowStyleEditor(false);
                      }}
                      className="flex items-center justify-center border-none bg-transparent cursor-pointer"
                      style={{ width: 24, height: 24, color: 'var(--text-tertiary)' }}
                    >
                      <X size={12} />
                    </button>
                  </div>
                  <div
                    style={{
                      maxHeight: 400,
                      overflow: 'auto',
                    }}
                  >
                    {/* Override the StylePanel's built-in width and border */}
                    <div
                      style={{
                        width: '100%',
                      }}
                    >
                      <StylePanel
                        styles={selectedNodeStyles}
                        onStyleChange={handleStyleChange}
                      />
                    </div>
                  </div>
                </div>
              )}

              {/* Animation attributes */}
              {template.animationAttrs && Object.keys(template.animationAttrs).length > 0 && (
                <div
                  style={{
                    border: '1px solid var(--border-default)',
                    borderRadius: 'var(--radius-lg)',
                    overflow: 'hidden',
                  }}
                >
                  <div
                    style={{
                      height: 36,
                      padding: '0 12px',
                      borderBottom: '1px solid var(--border-default)',
                      backgroundColor: 'var(--bg-secondary)',
                      display: 'flex',
                      alignItems: 'center',
                    }}
                  >
                    <span
                      className="font-medium"
                      style={{ fontSize: 'var(--text-xs)', color: 'var(--text-primary)' }}
                    >
                      Animation Attributes
                    </span>
                  </div>
                  <div style={{ padding: '8px 12px' }}>
                    {Object.entries(template.animationAttrs).map(([key, value]) => (
                      <div
                        key={key}
                        className="flex items-center"
                        style={{
                          gap: 8,
                          fontSize: 'var(--text-xs)',
                          fontFamily: 'var(--font-mono)',
                          padding: '3px 0',
                        }}
                      >
                        <span style={{ color: '#f59e0b' }}>{key}</span>
                        <span style={{ color: 'var(--text-tertiary)' }}>=</span>
                        <span style={{ color: 'var(--accent-text)' }}>"{value}"</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Footer */}
        {template && (
          <div
            className="flex items-center shrink-0"
            style={{
              height: 52,
              padding: '0 16px',
              borderTop: '1px solid var(--border-default)',
              gap: 8,
            }}
          >
            {onDuplicate && (
              <button
                onClick={() => onDuplicate(template.id)}
                className="flex items-center cursor-pointer"
                style={{
                  gap: 6,
                  height: 32,
                  padding: '0 12px',
                  border: '1px solid var(--border-default)',
                  borderRadius: 'var(--radius-md)',
                  backgroundColor: 'transparent',
                  fontSize: 'var(--text-xs)',
                  fontWeight: 500,
                  color: 'var(--text-primary)',
                  fontFamily: 'var(--font-sans)',
                }}
              >
                <Copy size={13} />
                Duplicate
              </button>
            )}
            <button
              className="flex items-center cursor-pointer"
              onClick={async () => {
                const html = nodeToHtml(template.structure);
                await navigator.clipboard.writeText(html);
                toast.success('HTML copied to clipboard');
              }}
              style={{
                gap: 6,
                height: 32,
                padding: '0 12px',
                border: '1px solid var(--border-default)',
                borderRadius: 'var(--radius-md)',
                backgroundColor: 'transparent',
                fontSize: 'var(--text-xs)',
                fontWeight: 500,
                color: 'var(--text-primary)',
                fontFamily: 'var(--font-sans)',
              }}
            >
              <Code size={13} />
              Copy HTML
            </button>
            <button
              className="flex items-center cursor-pointer"
              onClick={async () => {
                const script = generateDesignerScript(template.structure, template.animationAttrs);
                await navigator.clipboard.writeText(script);
                toast.success('Designer API script copied', {
                  description: 'Paste into Webflow Designer App or use with the Designer API.',
                  duration: 4000,
                });
              }}
              style={{
                gap: 6,
                height: 32,
                padding: '0 12px',
                border: 'none',
                borderRadius: 'var(--radius-md)',
                backgroundColor: 'var(--accent)',
                color: '#ffffff',
                fontSize: 'var(--text-xs)',
                fontWeight: 500,
                fontFamily: 'var(--font-sans)',
                marginLeft: 'auto',
                transition: 'background-color var(--duration-fast)',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.backgroundColor = 'var(--accent-hover)';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.backgroundColor = 'var(--accent)';
              }}
            >
              Push to Webflow
            </button>
          </div>
        )}
      </div>
    </>
  );
}

// ── Helper components ──

function StructureNode({
  node,
  depth,
  path,
  selectedPath,
  onSelect,
}: {
  node: TemplateNode;
  depth: number;
  path: number[];
  selectedPath: number[] | null;
  onSelect: (path: number[]) => void;
}) {
  const hasChildren = node.children && node.children.length > 0;
  const isSelected = selectedPath !== null && path.join('-') === selectedPath.join('-');

  return (
    <div>
      <div
        className="flex items-center"
        style={{
          height: 26,
          paddingLeft: depth * 16 + 8,
          gap: 6,
          fontSize: 'var(--text-xs)',
          borderRadius: 'var(--radius-sm)',
          backgroundColor: isSelected ? 'var(--accent-subtle)' : 'transparent',
          cursor: 'pointer',
        }}
        onClick={() => onSelect(path)}
        onMouseEnter={(e) => {
          if (!isSelected) e.currentTarget.style.backgroundColor = 'var(--surface-hover)';
        }}
        onMouseLeave={(e) => {
          if (!isSelected) e.currentTarget.style.backgroundColor = 'transparent';
        }}
      >
        <span style={{ color: 'var(--text-tertiary)', fontWeight: 500, minWidth: 32, flexShrink: 0 }}>
          {node.tag}
        </span>
        <span
          style={{
            fontFamily: 'var(--font-mono)',
            color: 'var(--accent-text)',
            backgroundColor: isSelected ? 'var(--accent)' : 'var(--accent-subtle)',
            ...(isSelected ? { color: 'var(--text-on-accent)' } : {}),
            padding: '0 4px',
            borderRadius: 'var(--radius-sm)',
            whiteSpace: 'nowrap',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
          }}
        >
          .{node.className}
        </span>
        {node.text && (
          <span
            style={{
              color: 'var(--text-tertiary)',
              whiteSpace: 'nowrap',
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              fontStyle: 'italic',
            }}
          >
            "{node.text}"
          </span>
        )}
      </div>
      {hasChildren &&
        node.children!.map((child, i) => (
          <StructureNode
            key={`${child.className}-${i}`}
            node={child}
            depth={depth + 1}
            path={[...path, i]}
            selectedPath={selectedPath}
            onSelect={onSelect}
          />
        ))}
    </div>
  );
}

function CollapsibleSection({ title, defaultOpen = false, children }: { title: string; defaultOpen?: boolean; children: React.ReactNode }) {
  const [open, setOpen] = useState(defaultOpen);

  return (
    <div
      style={{
        border: '1px solid var(--border-default)',
        borderRadius: 'var(--radius-lg)',
        overflow: 'hidden',
      }}
    >
      <button
        onClick={() => setOpen((prev) => !prev)}
        className="flex items-center justify-between"
        style={{
          width: '100%',
          height: 36,
          padding: '0 12px',
          border: 'none',
          borderBottom: open ? '1px solid var(--border-default)' : '1px solid transparent',
          backgroundColor: 'var(--bg-secondary)',
          cursor: 'pointer',
          fontFamily: 'var(--font-sans)',
        }}
      >
        <span
          className="font-medium"
          style={{ fontSize: 'var(--text-xs)', color: 'var(--text-primary)' }}
        >
          {title}
        </span>
        <ChevronDown
          size={14}
          style={{
            color: 'var(--text-tertiary)',
            transform: open ? 'rotate(0deg)' : 'rotate(-90deg)',
            transition: 'transform var(--duration-fast)',
          }}
        />
      </button>
      {open && <div style={{ padding: 12 }}>{children}</div>}
    </div>
  );
}

function countNodes(node: TemplateNode): number {
  return 1 + (node.children?.reduce((sum, child) => sum + countNodes(child), 0) ?? 0);
}
