import { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { prisma } from '../../db/client.js';
import { requireAuth } from '../../middleware/auth.js';
import { ValidationError, NotFoundError } from '../../utils/errors.js';
import { logActivity } from '../../utils/activity-logger.js';

// ─── Schemas ────────────────────────────────────────────────────

const projectIdSchema = z.object({
  projectId: z.string().uuid(),
});

const breakpointSchema = z.object({
  baseFontSize: z.number().min(8).max(32),
  idealWidth: z.number().min(200).max(3840),
  minWidth: z.number().min(200).max(3840),
  maxWidth: z.number().min(200).max(3840),
});

const scalingConfigBodySchema = z.object({
  name: z.string().min(1).max(100).default('Default'),
  config: z.object({
    desktop: breakpointSchema,
    tablet: breakpointSchema,
    mobileLandscape: breakpointSchema,
    mobilePortrait: breakpointSchema,
  }),
  isDefault: z.boolean().default(false),
});

// ─── CSS Generation ─────────────────────────────────────────────

interface BreakpointConfig {
  baseFontSize: number;
  idealWidth: number;
  minWidth: number;
  maxWidth: number;
}

interface ScalingConfigData {
  desktop: BreakpointConfig;
  tablet: BreakpointConfig;
  mobileLandscape: BreakpointConfig;
  mobilePortrait: BreakpointConfig;
}

/**
 * Generate a CSS clamp() value for fluid typography.
 *
 * clamp(minSize, preferred, maxSize)
 * - minSize: baseFontSize at minWidth
 * - maxSize: baseFontSize at maxWidth
 * - preferred: a vw-based calculation that scales between minWidth and maxWidth
 */
function generateClampValue(bp: BreakpointConfig): string {
  const minFontPx = bp.baseFontSize * (bp.minWidth / bp.idealWidth);
  const maxFontPx = bp.baseFontSize * (bp.maxWidth / bp.idealWidth);

  // Slope: (maxFont - minFont) / (maxWidth - minWidth)
  const slope = (maxFontPx - minFontPx) / (bp.maxWidth - bp.minWidth);
  const slopeVw = slope * 100;

  // Y-intercept: minFont - slope * minWidth
  const interceptPx = minFontPx - slope * bp.minWidth;

  const minRem = (minFontPx / 16).toFixed(4);
  const maxRem = (maxFontPx / 16).toFixed(4);
  const interceptRem = (interceptPx / 16).toFixed(4);
  const slopeVwStr = slopeVw.toFixed(4);

  return `clamp(${minRem}rem, ${interceptRem}rem + ${slopeVwStr}vw, ${maxRem}rem)`;
}

function generateScalingCSS(config: ScalingConfigData): string {
  const lines: string[] = [];

  lines.push('/* Forge Scaling System — Fluid Typography with clamp() */');
  lines.push('/* Generated by Forge. Do not edit manually. */');
  lines.push('');

  // Desktop (default — no media query)
  lines.push('html {');
  lines.push(`  font-size: ${generateClampValue(config.desktop)};`);
  lines.push('}');
  lines.push('');

  // Tablet
  lines.push(`@media (max-width: ${config.tablet.maxWidth}px) {`);
  lines.push('  html {');
  lines.push(`    font-size: ${generateClampValue(config.tablet)};`);
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Mobile Landscape
  lines.push(`@media (max-width: ${config.mobileLandscape.maxWidth}px) {`);
  lines.push('  html {');
  lines.push(`    font-size: ${generateClampValue(config.mobileLandscape)};`);
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Mobile Portrait
  lines.push(`@media (max-width: ${config.mobilePortrait.maxWidth}px) {`);
  lines.push('  html {');
  lines.push(`    font-size: ${generateClampValue(config.mobilePortrait)};`);
  lines.push('  }');
  lines.push('}');

  return lines.join('\n');
}

// ─── Routes ─────────────────────────────────────────────────────

export async function scalingRoutes(app: FastifyInstance) {
  app.addHook('preHandler', requireAuth);

  // GET /api/scaling/:projectId — Get scaling config (create default if none exists)
  app.get('/:projectId', async (request, reply) => {
    const params = projectIdSchema.safeParse(request.params);
    if (!params.success) throw new ValidationError(params.error.flatten().fieldErrors);

    const project = await prisma.project.findFirst({
      where: { id: params.data.projectId, userId: request.user.userId },
    });
    if (!project) throw new NotFoundError('Project');

    let config = await prisma.scalingConfig.findFirst({
      where: { projectId: params.data.projectId, userId: request.user.userId },
      orderBy: { createdAt: 'desc' },
    });

    // Create a default config if none exists
    if (!config) {
      config = await prisma.scalingConfig.create({
        data: {
          userId: request.user.userId,
          projectId: params.data.projectId,
          name: 'Default',
          config: {
            desktop: { baseFontSize: 16, idealWidth: 1440, minWidth: 992, maxWidth: 1920 },
            tablet: { baseFontSize: 16, idealWidth: 834, minWidth: 768, maxWidth: 991 },
            mobileLandscape: { baseFontSize: 16, idealWidth: 550, minWidth: 480, maxWidth: 767 },
            mobilePortrait: { baseFontSize: 16, idealWidth: 375, minWidth: 320, maxWidth: 479 },
          },
          isDefault: true,
        },
      });
    }

    return reply.send({ data: config });
  });

  // PUT /api/scaling/:projectId — Update scaling config
  app.put('/:projectId', async (request, reply) => {
    const params = projectIdSchema.safeParse(request.params);
    if (!params.success) throw new ValidationError(params.error.flatten().fieldErrors);

    const body = scalingConfigBodySchema.safeParse(request.body);
    if (!body.success) throw new ValidationError(body.error.flatten().fieldErrors);

    const project = await prisma.project.findFirst({
      where: { id: params.data.projectId, userId: request.user.userId },
    });
    if (!project) throw new NotFoundError('Project');

    const existing = await prisma.scalingConfig.findFirst({
      where: { projectId: params.data.projectId, userId: request.user.userId },
    });

    let config;
    if (existing) {
      config = await prisma.scalingConfig.update({
        where: { id: existing.id },
        data: {
          name: body.data.name,
          config: body.data.config,
          isDefault: body.data.isDefault,
        },
      });
    } else {
      config = await prisma.scalingConfig.create({
        data: {
          userId: request.user.userId,
          projectId: params.data.projectId,
          name: body.data.name,
          config: body.data.config,
          isDefault: body.data.isDefault,
        },
      });
    }

    logActivity({
      userId: request.user.userId,
      projectId: params.data.projectId,
      action: 'SETTINGS_UPDATED',
      details: { type: 'scaling_config', name: body.data.name },
    });

    return reply.send({ data: config });
  });

  // POST /api/scaling/:projectId/generate — Generate CSS for scaling system
  app.post('/:projectId/generate', async (request, reply) => {
    const params = projectIdSchema.safeParse(request.params);
    if (!params.success) throw new ValidationError(params.error.flatten().fieldErrors);

    const project = await prisma.project.findFirst({
      where: { id: params.data.projectId, userId: request.user.userId },
    });
    if (!project) throw new NotFoundError('Project');

    const config = await prisma.scalingConfig.findFirst({
      where: { projectId: params.data.projectId, userId: request.user.userId },
      orderBy: { createdAt: 'desc' },
    });

    if (!config) {
      throw new ValidationError({ config: ['No scaling config found for this project. Create one first.'] });
    }

    const scalingData = config.config as unknown as ScalingConfigData;
    const css = generateScalingCSS(scalingData);

    return reply.send({ data: { css, configId: config.id } });
  });
}
